version: '2'
services:
  app:
    image: library/debian
    working_dir: /var/www
    environment:
      - APP_KEY=null
      - DB_HOST=null
      - DB_PORT=27017
      - DB_NAME=null
      - DB_DRIVER=null
      - DB_USER=null
      - DB_PASS=null

